# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0002_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Tiene_Tipo_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Usuario_idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Tipo_Usuario')),
                ('Usuario_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Usuario')),
            ],
        ),
    ]
