# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0003_usuario_tiene_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=80)),
                ('cantidad_disponible', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('latitud', models.CharField(max_length=40)),
                ('longitud', models.CharField(max_length=40)),
                ('Ciudad_idCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Arrienda_Propiedad',
            fields=[
                ('fecha_inicio', models.DateTimeField(primary_key=True, serialize=False)),
                ('fecha_termino', models.DateTimeField()),
                ('Propiedad_idPropiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Propiedad')),
                ('Usuario_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Ocupa_Propiedad',
            fields=[
                ('fecha_inicio', models.DateTimeField(primary_key=True, serialize=False)),
                ('fecha_termino', models.DateTimeField()),
                ('Propiedad_idPropiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Propiedad')),
                ('Usuario_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='Tipo_Propiedad_idTipo_Propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Tipo_Propiedad'),
        ),
        migrations.AddField(
            model_name='foto',
            name='Propiedad_idPropiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Propiedad'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='Region_idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Region'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='Comuna_idComuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Comuna'),
        ),
    ]
