# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0004_auto_20161215_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Califica_Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calificacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=500, null=True)),
                ('Propiedad_idPropiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Propiedad')),
                ('Usuario_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrendados.Usuario')),
            ],
        ),
    ]
