# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0005_usuario_califica_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Califica_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calificacion', models.IntegerField()),
                ('Usuario_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario1', to='arrendados.Usuario')),
                ('Usuario_idUsuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario2', to='arrendados.Usuario')),
            ],
        ),
    ]
