# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0006_usuario_califica_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
