# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0007_auto_20161219_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
