# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0009_auto_20161219_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='check_offer',
            field=models.NullBooleanField(),
        ),
    ]
