# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0010_usuario_check_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='check_offer',
            field=models.BooleanField(default=True),
        ),
    ]
