# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendados', '0011_auto_20161222_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='check_offer',
            field=models.NullBooleanField(default=False),
        ),
    ]
